---
language: python
python:
  - '3.6'
before_install:
  - openssl aes-256-cbc -K $encrypted_e261e990e5c8_key -iv $encrypted_e261e990e5c8_iv -in secrets.tar.enc -out secrets.tar -d
  - tar xvf secrets.tar
  - mv google_compute_engine /home/travis/.ssh/
  - chmod 0600 /home/travis/.ssh/google_compute_engine

install:
  - pip install molecule apache-libcloud pycrypto paramiko

script:
  - molecule test

env:
  matrix:
    - GCE_CREDENTIALS_FILE="$(pwd)/credentials.json"
  global:
    - secure: m2Tzf9xXhC72cqUnOCG2BS2NfFY3PAALDh8LTHibm+P5MFAJFJ2mUrGlZEeyvUZrZ9bWKzcYEAPWob0ZVxSQ0dFU+mPPGNwaqZJzah5ZIXdZ1ZGbY6EOUdWvTeiyYKv3yvsCYb/tK6KLFzqDUOjM4Sz7N/scqoOOE0D045UjGhCkdrljsuTBFj5j06BftUC4N70awN+tHU7ssQL48yHePHEPjeyIBdOwcmKtmxdPOn/Pq0anjpl5gSvd2bfcicCcuANWwONTENeLrq0IctrRvh+OfSqTooS2bQX7I3nmn5ObJlCzzQQMF6cJ/kYiRGjxUq8whY6nup6NNHJlb4Nn+JJfzC2pSvnxjVJt+W38bd//ecVD9gZC4oJ3zB3Z9csE9YxISMf4en3jyfaDctzXbf8vDccsYcj33lVZikFdeZGTYh8zjo+6HQgLdqiVew+JSccvWNzYGJRIOKObTxoRgoJS/RyOAybJwsfMGPTSgZKohMMByTSztUviWvDPtaNKnwdVxhpPe4BnAbISIo8M1mkd2js6AiJfSRm8tDM9sgklnXmLnwZNrdFdakETm1v70Lntsi/g1TXDPFYeJJ2pO5cLsOiB5yPXqnIc7ECAZAxydXDQP8oUhuGje/hb4MEXSwbYTc4jE5bfktsci2EY0qPsC3UR9X2PbyEwf2Oko5Q=
    - secure: guRWVGBaM1Bj4Iq1/DnSkZUXInmaLHE2u2dGGavgDFrZjU0BlMoGddMQeMxKeNCpc1jZXJfNxg0mJcvjFIyd7kRyL1EERz1b1L+qqvwPoyGLU3IZ00SDo9FUOKpNxdcZIYndSvVLpyIBlPKwZMTkurMIJ4v8MHRXcImkWG5GyLBmkvEsFJ8PCpF2DbmX+w06zbSqDNH7Bdri1N+ONgPwm0e+Wl9N+7wguFixkIXjjQwgTbcTCw+4HZI+OOxe9AGB45E/P74dcAA4/dqhfxqGNP8LPAZQJ+JP8pK10j1i9MaKZnikf4qsU2tLds2d+FAoqO/Ed5lOeXMS1e8xrNSo2yRG/beVYH6uzESHFRddZAYCtqX1MYfCzbXXRL0wJn5qw7mbET8sCxf/nPEPVDDEjCQ6+TL+mqLKOUQRjA74LWk5tEXllETcVOfKUHhhH42ivEzlhtshCVx+bDN9sX1lSHu7L/yXkwZzSdw6zY7asFRVu7H+YgIpUi54ASve/WnaluwR+dxmM32niCknZI672RkaRUCOkWaYSXZKoFj6Onp/S15G/9JOrCTVUEyNu/09K9dtcNDgSgBfJH/2NjuGhkZ+rOEudsx1iKJDTb3C1RElKBGoBoA31buwkgvdRD+DFIjhA3bw4vB40ulqpHRRCJRogkNoKwTseEZ4XVP7KaU=
    - secure: cm9hNfFpel/a+TDyJ6amElZNMVDBiVMcOv6PxCar1eEqplJBYmhAdlcYv7pQwtHi1U0u16dotTISs4ylFHXcgJM0I5ykUTjRZT8wgHKXjIYLD25vWy/Dge3Ctw+l99rs599+OWS9FvXvzv8/q8ZryadlaH9q5jgms8hX1djaMhjVfcZjfoKYB/7XtwbQi9RQBLB4fGNkOPvcKIliWQhFmPNSU5813X9Rq+rY8qSwiRnzECv0wH8osrp4P6/2N8IGHoTm5NPnVUYFEe4Nt4+8W39QxPbprOmTajdZtqFOrNpEpWANM52NdRiPKwCtEOYQJIxvsgrtbyKQLQ4DFzSxS1f9vYanyOQM+GvIR0jzXP1SyrjTUdTZGQiCrIg1kKUAkcpXVlcnxocX58u0Yhhl5xg5q8G1g2uLg2pyELBze6/Ns4piqpGdky+kusFKZ2ho4TUaNjjk9EYnw/NMuSSI/0R/0IKTa+Rm7Wd9HXMvSBgyoDIZNtkUj3JJqJYPT395wjmjj6tEcPeD7iGehGXrz42lG2BJYgvC9XA9/C22X3hgi5k+XrqtBmDivvCWOr2PB2dyphB/GNVsQucjpww0vE1Rzzd5535L6J90viyc9r+bRBE2/NR6J7jqJwa/hc7xAWun1BxXpHIVVKijlW0823HMB+zuhS6o/kMZwxAblZ0=

notifications:
  slack:
    rooms:
      secure: K59G806bEMc0REEeYar/7SPH1svjsIVIWGOpjeScghRB12dvLCcTSQtiwheVCIv4ArkQmLct4p9iekgUziRM/w+YNhInBe3FJ+4J4qaBXHPH6HyDyZuycy7FiwUa/859EN5RW77cbwjsa3G3JHmAd5iFCNVOfQL+FoRiE5q5ALo1Cfvu/oqxJaQ9XG+N+HRihuvQcIwSfMWUH73SykziQGyqMiWTkM7iXZh8XBlhDuJIZ+b8E/fRoakzT6JXkXmBnSfQ2eHe2KOZeWtH2wi8e4QaV+GT7oFeY7hCBZ3NgtzBHaG8t+kikz0G6yS1rfmW1YZA5ZNDe657E7BDkiEAaKKGQ3j/qbNWxncwGVlfUAExZjfDk18CzT9ASVo0qA9QXDUoOzaQ58vQCMs57ylhS4iyx4FAThn8mQkPaLGJDCy0e6/pnGgXwymKiZ8lyrWmHH/5l7Vjij0HoVYGV7bdKxqoVJoettlM/PaU8dpQ8ztcVZ+kGhkHlEhtpUGBcOqcrwWJZ7SAo2ChUwBTykI/5dTNlZbO72xeTe1SSQHE9vAzBeZzgWbXs2YP5l9aoOKZCquDM+Jju9LI5nLm5/0F4Hp9i9O1d0IUo+UN8CxkVqpSOgaFCPeQwfLQlpxZTdTEBYPtbaczF1rvTdTMxY7sLwvNd3uEwoA/TLe4E/fXobk=
